version: "3.4"

services:
  python-project:
    container_name: python-project
    tty: true
    image: python-project:dev
    stdin_open: true
    build:
      context: .
      target: development
    volumes:
      - .:/src
    env_file: .env
