version: "3.4"

services:
  python-project:
    tty: true
    image: "python-project"
    stdin_open: true
    build:
      context: .
      target: "development"
    volumes:
      - ".:/src"
    env_file: .env